site:
  name: RVB Data Sciences
  site: 'https://rvbcorp.com'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: SWINTeLMmBksNKVE3LoUttMuoiQOQ4uQ3_tGF4r6tW0

# Default SEO metadata
metadata:
  title:
    default: RVB Data Sciences
    template: '%s â€” RVB Data Sciences'
  description: "We offer tailored digital solutions for businesses of all sizes.
  Our team specializes in creating dynamic, user-friendly websites that drive growth and improve online presence.
  Contact us today to transform your digital landscape."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: RVB Data Sciences
    images:
      - url: '~/assets/images/about-us-main.webp'
        width: 1200
        height: 628
    type: website

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: false

    list:
      isEnabled: true
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: false

    category:
      isEnabled: true
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: false

    tag:
      isEnabled: true
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: 'G-NRKP9WCSL2'

ui:
  theme: 'dark:only' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
